### ISSUE TITLE
docs: update README.md

### ISSUE THREAD

**Issue by gmacario** [aleche28/aleche28#1]
I believe [this line](https://github.com/aleche28/aleche28/blob/main/README.md?plain=1#L2) is partially correct

Blocked-by: https://arol.atlassian.net/browse/IH-52

**Comment by aleche28** [comment]
Still a week left😂

**Comment by gmacario** [comment]
> Still a week left😂

Pinging after two weeks 😉

**Comment by aleche28** [comment]
Fixed it!
